config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#new'
  post 'items' => 'items#create'
  delete 'items/:id' => 'items#destroy', as: 'item'
# resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disc.rb
class Disc < ApplicationRecord
	# NESTED_ALLOWED_PARAMS = [:id, :_destroy, :number]


     has_many :songs, dependent: :destroy
     belongs_to :item

	#親のフォームに子のフィールドを追加すると、一緒に子の新規登録ができる
     accepts_nested_attributes_for :songs, allow_destroy: true


end

app/models/item.rb
class Item < ApplicationRecord
	# ALLOWED_PARAMS = [:name]

     has_many :discs, dependent: :destroy

     #親のフォームに子のフィールドを追加すると、一緒に子の新規登録ができる
     accepts_nested_attributes_for :discs, allow_destroy: true

end

app/models/song.rb
class Song < ApplicationRecord

      belongs_to :disc

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
      @item = Item.new
      @items = Item.all
      @item.discs.build
      @discs = Disc.all
      # @disc.songs.build
      @songs = Song.all
  end

  def create
      item = Item.new(item_params)
      item.save
      redirect_to "/"
  end

  def destroy
      item = Item.find(params[:id])
      item.destroy
      redirect_to "/"
  end







      private
# 子要素・孫要素も一緒に許可する。　idと_destroyを必ず入れる
      def item_params
      	  params.require(:item).permit(:name,
      	  	                            discs_attributes: [:id, :number, :_destroy,
      	  	                            songs_attributes: [:id, :name, :_destroy]])
      end



end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/items/_disc_fields.html.erb
<!-- 必ず nested-fields　というクラスをつける　削除機能に必須　-->
<div class="nested-fields">

    <div class="form-group">
    <%= f.label 'Disc number' %><br>
    <%= f.number_field :number %>
    <!-- このフォームを削除する -->
    <%= link_to_remove_association "Discを削除", f %>
    </div>

    <div class="songs">
      <%= f.fields_for :songs do |song| %>
        <%= render 'song_fields', f: song %>
      <% end %>

      <%= link_to_add_association "add song", f, :songs %>
      <br><br>
    </div>
</div>



app/views/items/_song_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label '曲名' %>
    <%= f.text_field :name %>
     <!-- このフォームを削除する -->
    <%= link_to_remove_association "曲を削除", f %>
  </div>
</div>

app/views/items/new.html.erb
<h1>ここにフォームを表示します</h1>

<!-- 親のフォーム欄記述 -->
  <%= form_for(@item) do |f| %>
    <%= f.label 'CD名' %><br>
    <%= f.text_field :name %>


  <div class='disc-form'>
    <!-- 子のモデルを指定 -->
    <%= f.fields_for :discs do |builder| %>
      <!-- フォーム欄を別で用意しrenderで指定　モデル名_fields -->
      <%= render 'disc_fields', f: builder %>
    <% end %>

      <!-- 子モデルのフォームを追加する -->
      <div id="links">
      <%= link_to_add_association "add discs", f, :discs %><br/>
      </div>

  </div>

  <%= f.submit 'Create CD' %><br><br><br>



  <%= f.label :CDを選択 %><br>
  <!-- 選択フォームの表示 -->
  <%= f.select :id, Item.order(:name).map { |g| [g.name, g.id] }, include_blank: true %>



 <% end %>


<h1>Item一覧</h1>

  <% @items.each do |item| %>

    <p><%= item.name %>
       <%= item.id %></p>
    <%= link_to "Destroy", item_path(item.id), method: :delete %>


  <% end %>


<h1>Disc一覧</h1>

  <% @discs.each do |disc| %>

    <p><%= disc.number %>
       <%= disc.item_id %>
       <%= disc.id %>
       </p>

  <% end %>


<h1>曲名一覧</h1>

  <% @songs.each do |song| %>

    <p><%= song.name %>
       <%= song.disc_id %></p>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prototype</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>